import './assets/styles/main.css';
import './assets/styles/components.css';
import './assets/styles/views.css';
import { loadState, saveState, resetState } from './services/storageService.js';
import { getSession, setSession, clearSession } from './services/authService.js';
import { validateEnrollment } from './logic/enrollmentValidator.js';
import { jsPDF } from 'jspdf';

let state = loadState();
let session = getSession() || { role: 'student', studentId: 'stu-001' };
let toastTimer;

const app = document.querySelector('#app');
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const currentStudent = () => state.students.find((student) => student.id === session.studentId) || state.students[0];
const labById = (id) => state.laboratories.find((lab) => lab.id === id);
const scheduleById = (lab, id) => lab?.schedules.find((slot) => slot.id === id);
const occupancy = (lab, scheduleId) => state.enrollments.filter((item) => item.laboratoryId === lab.id && item.scheduleId === scheduleId).length;
const notify = (message, type = 'success') => { clearTimeout(toastTimer); const node = document.querySelector('#toast'); if (!node) return; node.className = `toast ${type}`; node.textContent = message; node.hidden = false; toastTimer = setTimeout(() => { node.hidden = true; }, 3200); };

function navigate(path) { window.location.hash = path; }

function nav() {
	const admin = session.role === 'admin';
	const route = (window.location.hash.replace('#/', '').split('?')[0] || 'catalog');
	const link = (path, label) => `<a class="${route === path ? 'active' : ''}" href="#/${path}">${label}</a>`;
	return `<header class="topbar"><a class="brand" href="#/catalog"><span class="brand-mark">L</span><span>labora</span></a><nav class="nav-links">${link('catalog', 'Catálogo')}${admin ? `${link('admin-dashboard', 'Dashboard')}${link('admin-management', 'Gestión')}` : `${link('enrollment', 'Matricular')}${link('my-enrollments', 'Mis matrículas')}`}</nav><div class="session"><span class="role-badge">${admin ? 'Administrador' : esc(currentStudent().name)}</span><button class="icon-button" data-action="toggle-role" title="Cambiar rol">⇄</button><button class="icon-button" data-action="logout" title="Cerrar sesión">↪</button></div></header>`;
}

function layout(title, subtitle, content) { return `${nav()}<main class="page"><div class="page-heading"><div><p class="eyebrow">LABORA / ${session.role === 'admin' ? 'CONTROL ACADÉMICO' : 'PORTAL ESTUDIANTIL'}</p><h1>${title}</h1><p class="subtitle">${subtitle}</p></div></div>${content}</main><div id="toast" class="toast" hidden></div>`; }

function modal(title, content) { const node = document.createElement('div'); node.className = 'modal-backdrop'; node.innerHTML = `<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-heading"><div><p class="eyebrow">LABORA / FORMULARIO</p><h2 id="modal-title">${title}</h2></div><button class="icon-button" data-action="close-modal" aria-label="Cerrar">×</button></div>${content}</section>`; document.body.append(node); node.querySelectorAll('[data-action="close-modal"]').forEach((button) => button.addEventListener('click', () => node.remove())); node.addEventListener('click', (event) => { if (event.target === node) node.remove(); }); return node; }

function downloadEnrollmentsPdf() {
	const pdf = new jsPDF();
	const student = currentStudent();
	const mine = state.enrollments.filter((item) => item.studentId === session.studentId);
	let y = 22;
	pdf.setFillColor(79, 70, 229); pdf.rect(0, 0, 210, 12, 'F');
	pdf.setTextColor(23, 37, 84); pdf.setFontSize(22); pdf.text('LABORA', 20, y); y += 12;
	pdf.setFontSize(11); pdf.setTextColor(83, 96, 122); pdf.text('Comprobante de matrículas', 20, y); y += 12;
	pdf.setTextColor(23, 32, 61); pdf.setFontSize(12); pdf.text(`Estudiante: ${student.name}`, 20, y); y += 7; pdf.text(`Programa: ${student.program}`, 20, y); y += 7; pdf.text(`Fecha: ${new Date().toLocaleDateString('es-CO')}`, 20, y); y += 14;
	pdf.setFillColor(238, 242, 255); pdf.roundedRect(20, y - 6, 170, 12, 2, 2, 'F'); pdf.setTextColor(55, 48, 163); pdf.text(`Total de matrículas: ${mine.length}`, 26, y + 2); y += 18;
	mine.forEach((item, index) => { const lab = labById(item.laboratoryId); const slot = scheduleById(lab, item.scheduleId); if (y > 260) { pdf.addPage(); y = 22; } pdf.setDrawColor(226, 234, 242); pdf.roundedRect(20, y - 7, 170, 28, 2, 2, 'S'); pdf.setTextColor(23, 37, 84); pdf.setFontSize(12); pdf.text(`${index + 1}. ${lab.name}`, 26, y); pdf.setFontSize(9); pdf.setTextColor(83, 96, 122); pdf.text(`${lab.code}  |  ${slot.day} ${slot.start}-${slot.end}  |  ${lab.location}`, 26, y + 8); pdf.text(`Registrada: ${new Date(item.createdAt).toLocaleDateString('es-CO')}`, 26, y + 16); y += 37; });
	pdf.setFontSize(8); pdf.setTextColor(115, 128, 154); pdf.text('Documento generado por Labora - Gestión académica', 20, 285); pdf.save(`matriculas-${student.name.toLowerCase().replaceAll(' ', '-')}.pdf`); notify('PDF descargado correctamente.');
}

function labCard(lab) {
	const slots = lab.schedules.map((slot) => { const used = occupancy(lab, slot.id); const free = Math.max(lab.capacity - used, 0); const state = free === 0 ? 'full' : free <= Math.ceil(lab.capacity * .2) ? 'warning' : ''; return `<div class="schedule-row"><span><b>${slot.day}</b> ${slot.start}–${slot.end}</span><span class="availability ${state}">${free} libres</span></div>`; }).join('');
	const totalFree = lab.schedules.reduce((sum, slot) => sum + Math.max(lab.capacity - occupancy(lab, slot.id), 0), 0);
	const statusClass = !lab.active || totalFree === 0 ? 'inactive' : totalFree <= Math.ceil(lab.capacity * lab.schedules.length * .2) ? 'warning' : 'active';
	const statusLabel = !lab.active ? 'Inactivo' : totalFree === 0 ? 'Lleno' : statusClass === 'warning' ? 'Pocos cupos' : 'Disponible';
	return `<article class="lab-card"><div class="lab-top"><div><span class="code">${esc(lab.code)}</span><h3>${esc(lab.name)}</h3></div><span class="status ${statusClass}">${statusLabel}</span></div><p class="location">⌖ ${esc(lab.location)}</p><div class="capacity"><span>Aforo total</span><strong>${lab.capacity} personas</strong></div><div class="schedule-list">${slots}</div>${lab.active && session.role === 'student' ? `<button class="button primary full-width" data-action="enroll-lab" data-id="${lab.id}">Inscribirme <span>→</span></button>` : ''}</article>`;
}

function catalogView() { return layout('Catálogo de laboratorios', 'Consulta horarios, capacidad y disponibilidad en tiempo real.', `<section class="toolbar"><label class="search"><span>⌕</span><input id="catalog-search" placeholder="Buscar por nombre o código..." /></label><select id="catalog-filter"><option value="all">Todos los laboratorios</option><option value="active">Solo disponibles</option></select></section><section id="catalog-grid" class="lab-grid">${state.laboratories.map(labCard).join('')}</section>`); }

function enrollmentView() { const activeLabs = state.laboratories.filter((lab) => lab.active); const requestedId = new URLSearchParams(window.location.hash.split('?')[1] || '').get('lab'); const selectedLab = activeLabs.find((lab) => lab.id === requestedId) || activeLabs[0]; return layout('Nueva matrícula', 'Elige el laboratorio y el bloque que mejor se ajuste a tu horario.', `<form id="enrollment-form" class="form-panel"><div class="step-label"><span>01</span> Selección académica</div><label>Laboratorio<select name="laboratoryId" id="enroll-lab-select">${activeLabs.map((lab) => `<option value="${lab.id}" ${lab.id === selectedLab.id ? 'selected' : ''}>${esc(lab.name)} · ${lab.code}</option>`).join('')}</select></label><label>Horario disponible<select name="scheduleId" id="enroll-schedule-select">${selectedLab.schedules.map((slot) => `<option value="${slot.id}">${slot.day} · ${slot.start}–${slot.end} · ${Math.max(selectedLab.capacity - occupancy(selectedLab, slot.id), 0)} cupos</option>`).join('')}</select></label><div id="enroll-preview" class="validation-note good">✓ Verifica el horario antes de confirmar</div><button class="button primary" type="submit">Confirmar matrícula <span>→</span></button></form>`); }

function myEnrollmentsView() { const mine = state.enrollments.filter((item) => item.studentId === session.studentId); const cards = mine.length ? mine.map((item) => { const lab = labById(item.laboratoryId); const slot = scheduleById(lab, item.scheduleId); return `<article class="enrollment-card"><div class="enrollment-icon">${lab.code.slice(4, 7)}</div><div class="enrollment-info"><span class="code">${lab.code}</span><h3>${esc(lab.name)}</h3><p>${slot.day} · ${slot.start}–${slot.end} · ${lab.location}</p></div><button class="button danger-outline" data-action="cancel" data-id="${item.id}">Cancelar</button></article>`; }).join('') : '<div class="empty-state"><span>○</span><h3>Aún no tienes matrículas</h3><p>Explora el catálogo para encontrar tu próximo laboratorio.</p><a class="button primary" href="#/catalog">Ver catálogo</a></div>'; return layout('Mis matrículas', `${mine.length} laboratorio${mine.length === 1 ? '' : 's'} registrado${mine.length === 1 ? '' : 's'} para ${esc(currentStudent().name)}.`, `<section class="profile-strip"><div class="avatar">${currentStudent().name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div><strong>${esc(currentStudent().name)}</strong><span>${esc(currentStudent().program)}</span></div><span class="count-pill">${mine.length} / 4 inscritos</span><button class="button primary" data-action="download-pdf">Descargar PDF ↓</button></section><section class="enrollment-list">${cards}</section>`); }

function dashboardView() { const active = state.laboratories.filter((lab) => lab.active); const totalCapacity = active.reduce((sum, lab) => sum + lab.capacity * lab.schedules.length, 0); const totalUsed = state.enrollments.length; const average = active.length ? Math.round(active.reduce((sum, lab) => sum + Math.min((state.enrollments.filter((item) => item.laboratoryId === lab.id).length / (lab.capacity * lab.schedules.length)) * 100, 100), 0) / active.length) : 0; const dayCounts = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'].map((day) => state.enrollments.filter((item) => { const lab = labById(item.laboratoryId); return lab?.schedules.some((slot) => slot.id === item.scheduleId && slot.day === day); }).length); const maxDay = Math.max(...dayCounts, 1); return layout('Dashboard de ocupación', 'Una lectura rápida de la oferta académica y sus cupos.', `<section class="metric-grid"><div class="metric"><span>Matrículas activas</span><strong>${totalUsed}</strong><small>Registros confirmados</small></div><div class="metric"><span>Cupos disponibles</span><strong>${Math.max(totalCapacity - totalUsed, 0)}</strong><small>de ${totalCapacity} totales</small></div><div class="metric"><span>Ocupación promedio</span><strong>${average}%</strong><small>${active.length} laboratorios activos</small></div></section><section class="charts-grid"><div class="panel chart-panel"><div class="panel-heading"><div><h2>Ocupación por laboratorio</h2><p>Porcentaje de uso frente al aforo</p></div><span class="live-dot">● En vivo</span></div><div class="occupancy-list">${active.map((lab) => { const used = state.enrollments.filter((item) => item.laboratoryId === lab.id).length; const maximum = lab.capacity * lab.schedules.length; const percent = Math.min(Math.round((used / maximum) * 100), 100); return `<div class="occupancy-row"><div><strong>${esc(lab.name)}</strong><span>${used} matriculados · ${maximum - used} libres</span></div><div class="bar"><i style="width:${percent}%"></i></div><b>${percent}%</b></div>`; }).join('')}</div></div><div class="panel chart-panel"><div class="panel-heading"><div><h2>Demanda por día</h2><p>Matrículas distribuidas por jornada</p></div></div><div class="day-chart">${dayCounts.map((count, index) => `<div class="day-column"><span>${count}</span><i style="height:${Math.max((count / maxDay) * 100, 8)}%"></i><b>${['L', 'M', 'X', 'J', 'V'][index]}</b></div>`).join('')}</div></div></section>`); }

function managementView() { return layout('Gestión de laboratorios', 'Administra la oferta, los aforos y los horarios disponibles.', `<div class="panel"><div class="panel-heading"><div><h2>Oferta académica</h2><p>${state.laboratories.length} registros configurados</p></div><button class="button primary" data-action="new-lab">＋ Nuevo laboratorio</button></div><div class="admin-table"><div class="table-header"><span>Laboratorio</span><span>Horarios</span><span>Capacidad</span><span>Estado</span><span>Acciones</span></div>${state.laboratories.map((lab) => `<div class="table-row"><div><strong>${esc(lab.name)}</strong><small>${lab.code} · ${lab.location}</small></div><span>${lab.schedules.length} bloques</span><span>${lab.capacity} personas</span><span class="status ${lab.active ? 'active' : 'inactive'}">${lab.active ? 'Activo' : 'Inactivo'}</span><span class="row-actions"><button class="icon-button" data-action="edit-lab" data-id="${lab.id}" title="Editar">✎</button><button class="icon-button danger" data-action="delete-lab" data-id="${lab.id}" title="Eliminar">×</button></span></div>`).join('')}</div></div>`); }

function render() { const route = window.location.hash.replace('#/', '') || 'catalog'; const view = route === 'enrollment' && session.role === 'student' ? enrollmentView() : route === 'my-enrollments' && session.role === 'student' ? myEnrollmentsView() : route === 'admin-dashboard' && session.role === 'admin' ? dashboardView() : route === 'admin-management' && session.role === 'admin' ? managementView() : catalogView(); app.innerHTML = view; bindEvents(); }

function refresh() { state = saveState(state); render(); }
function bindEvents() {
	document.querySelector('[data-action="toggle-role"]')?.addEventListener('click', () => { session.role = session.role === 'admin' ? 'student' : 'admin'; setSession(session); render(); });
	document.querySelector('[data-action="logout"]')?.addEventListener('click', () => { clearSession(); session = { role: 'student', studentId: 'stu-001' }; setSession(session); notify('Sesión reiniciada'); render(); });
	document.querySelector('[data-action="download-pdf"]')?.addEventListener('click', downloadEnrollmentsPdf);
	document.querySelector('#catalog-search')?.addEventListener('input', (event) => { const query = event.target.value.toLowerCase(); document.querySelectorAll('.lab-card').forEach((card) => { card.hidden = !card.textContent.toLowerCase().includes(query); }); });
	document.querySelector('#catalog-filter')?.addEventListener('change', (event) => { document.querySelectorAll('.lab-card').forEach((card, index) => { card.hidden = event.target.value === 'active' && !state.laboratories[index].active; }); });
	document.querySelectorAll('[data-action="enroll-lab"]').forEach((button) => button.addEventListener('click', () => { navigate(`enrollment?lab=${button.dataset.id}`); }));
	document.querySelectorAll('[data-action="cancel"]').forEach((button) => button.addEventListener('click', () => openCancellationForm(button.dataset.id)));
	document.querySelector('#enroll-lab-select')?.addEventListener('change', updateScheduleOptions);
	document.querySelector('#enrollment-form')?.addEventListener('submit', submitEnrollment);
	document.querySelector('[data-action="new-lab"]')?.addEventListener('click', () => editLab());
	document.querySelectorAll('[data-action="edit-lab"]').forEach((button) => button.addEventListener('click', () => editLab(button.dataset.id)));
	document.querySelectorAll('[data-action="delete-lab"]').forEach((button) => button.addEventListener('click', () => { const lab = labById(button.dataset.id); if (!confirm(`¿Eliminar ${lab.name}?`)) return; state.laboratories = state.laboratories.filter((item) => item.id !== lab.id); state.enrollments = state.enrollments.filter((item) => item.laboratoryId !== lab.id); refresh(); notify('Laboratorio eliminado.'); }));
}

function updateScheduleOptions() { const lab = labById(document.querySelector('#enroll-lab-select').value); document.querySelector('#enroll-schedule-select').innerHTML = lab.schedules.map((slot) => `<option value="${slot.id}">${slot.day} · ${slot.start}–${slot.end} · ${Math.max(lab.capacity - occupancy(lab, slot.id), 0)} cupos</option>`).join(''); }
function submitEnrollment(event) { event.preventDefault(); const data = new FormData(event.currentTarget); const lab = labById(data.get('laboratoryId')); const slot = scheduleById(lab, data.get('scheduleId')); const result = validateEnrollment({ studentId: session.studentId, laboratory: lab, schedule: slot, state }); if (!result.valid) { notify(result.message, 'error'); return; } state.enrollments.push({ id: `enr-${Date.now()}`, studentId: session.studentId, laboratoryId: lab.id, scheduleId: slot.id, createdAt: new Date().toISOString() }); refresh(); notify('Matrícula confirmada correctamente.'); navigate('my-enrollments'); }
function editLab(id) { const lab = id ? labById(id) : { name: '', code: '', location: '', capacity: 20, active: true, schedules: [{ day: 'Lunes', start: '08:00', end: '10:00' }] }; const slot = lab.schedules[0] || { day: 'Lunes', start: '08:00', end: '10:00' }; const node = modal(id ? 'Editar laboratorio' : 'Nuevo laboratorio', `<form id="lab-form" class="modal-form"><label>Nombre del laboratorio<input name="name" required value="${esc(lab.name)}" placeholder="Ej. Inteligencia Artificial"></label><div class="form-grid"><label>Código<input name="code" required value="${esc(lab.code)}" placeholder="LAB-IA-05"></label><label>Aforo máximo<input name="capacity" type="number" min="1" required value="${lab.capacity}"></label></div><label>Ubicación<input name="location" required value="${esc(lab.location)}" placeholder="Edificio y sala"></label><div class="form-grid"><label>Día<select name="day">${['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'].map((day) => `<option ${day === slot.day ? 'selected' : ''}>${day}</option>`).join('')}</select></label><label>Estado<select name="active"><option value="true" ${lab.active ? 'selected' : ''}>Activo</option><option value="false" ${!lab.active ? 'selected' : ''}>Inactivo</option></select></label></div><div class="form-grid"><label>Inicio<input name="start" type="time" required value="${slot.start}"></label><label>Fin<input name="end" type="time" required value="${slot.end}"></label></div><div class="modal-actions"><button type="button" class="button danger-outline" data-action="close-modal">Cancelar</button><button class="button primary" type="submit">Guardar cambios</button></div></form>`); node.querySelector('#lab-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (data.get('start') >= data.get('end')) return notify('La hora de inicio debe ser anterior a la hora final.', 'error'); const values = { name: data.get('name').trim(), code: data.get('code').trim().toUpperCase(), location: data.get('location').trim(), capacity: Number(data.get('capacity')), active: data.get('active') === 'true' }; const schedule = { id: slot.id || `s-${Date.now()}`, day: data.get('day'), start: data.get('start'), end: data.get('end') }; if (id) Object.assign(lab, values, { schedules: [schedule, ...lab.schedules.slice(1)] }); else state.laboratories.push({ ...values, id: `lab-${Date.now()}`, schedules: [schedule] }); node.remove(); refresh(); notify(id ? 'Laboratorio actualizado.' : 'Laboratorio creado.'); }); }

function openCancellationForm(enrollmentId) { const enrollment = state.enrollments.find((item) => item.id === enrollmentId); const lab = labById(enrollment.laboratoryId); const node = modal('Cancelar matrícula', `<form id="cancel-form" class="modal-form"><div class="form-summary"><span class="enrollment-icon">${lab.code.slice(4, 7)}</span><div><strong>${esc(lab.name)}</strong><p>El cupo será liberado inmediatamente.</p></div></div><label>Motivo de cancelación<select name="reason"><option>Ya no necesito este laboratorio</option><option>Conflicto con otro horario</option><option>Otro motivo académico</option></select></label><label>Comentario adicional<textarea name="comment" rows="3" placeholder="Opcional"></textarea></label><div class="modal-actions"><button type="button" class="button" data-action="close-modal">Conservar matrícula</button><button class="button danger-solid" type="submit">Confirmar cancelación</button></div></form>`); node.querySelector('#cancel-form').addEventListener('submit', (event) => { event.preventDefault(); state.enrollments = state.enrollments.filter((item) => item.id !== enrollmentId); node.remove(); refresh(); notify('Matrícula cancelada. El cupo fue restaurado.'); }); }

window.addEventListener('hashchange', render);
setSession(session);
render();
